ALTER TABLE users DROP COLUMN IF EXISTS name;
ALTER TABLE users DROP COLUMN IF EXISTS surname;
ALTER TABLE users DROP COLUMN IF EXISTS weight;
ALTER TABLE users DROP COLUMN IF EXISTS height;
ALTER TABLE users DROP COLUMN IF EXISTS age;
ALTER TABLE users DROP COLUMN IF EXISTS workModel;
ALTER TABLE users DROP COLUMN IF EXISTS workFutureModel;
ALTER TABLE users DROP COLUMN IF EXISTS gender;